export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const apiKey = process.env.REACT_APP_GOOGLE_API_KEY;

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        {children}
        <script
          src={`https://maps.googleapis.com/maps/api/js?key=${apiKey}&libraries=places`}
          defer
        />
      </body>
    </html>
  );
}
